# Generated by Django 3.1.6 on 2022-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Laptop & Accessory', 'Laptop & Accessory'), ('Mobile & Accessory', 'Mobile & Accessory'), ('Mobile Phone', 'Mobile Phone'), ('Others', 'Others')], default='Fashion', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
