# Generated by Django 3.1.6 on 2022-12-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221212_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='idduser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
            preserve_default=False,
        ),
    ]
