# Generated by Django 3.1.6 on 2022-12-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orderplaced_idduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='idduser',
        ),
    ]
