# Generated by Django 3.1.6 on 2022-12-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_orderplaced_idduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
            preserve_default=False,
        ),
    ]
