# Generated by Django 3.1.6 on 2022-12-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_orderplaced_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
