# Generated by Django 3.1.6 on 2022-12-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20221215_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='userid',
            new_name='userprofile',
        ),
    ]
