# Generated by Django 3.1.6 on 2022-12-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20221215_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
