# Generated by Django 3.1.6 on 2022-12-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_orderplaced_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='userprofile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
            preserve_default=False,
        ),
    ]
