# Generated by Django 3.1.6 on 2022-12-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20221215_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='userprofile',
            new_name='userprofileid',
        ),
    ]
